{ 
  server: {
    port: 8080,
    readTimeout: 3,
    writeTimeout: 3,
    maxHeaderBytes: 1000
  },
  auth: {
    private: "6E232E81CAB6D89C12C8975675ECE114199ACBFDF093AF260B92A1D7EE881F6A"
  },
  database: {
    config: {
      driver: "sqlite3",
      file: "local.db"
    },
    schema : {
      
    }
  },
}